### ISSUE TITLE
Sort Posts by date desc to match the view on my blog?

### ISSUE THREAD

**Issue by swartzrock** [cwxyz007/vscode-hexo-utils#11]
Hi, love this plugin! It would be great to sort the posts under POST by date descending instead of alphabetically, so the order matches their appearance on my blog. Thanks!

**Comment by cwxyz007** [comment]
This idea is on the [todo list](https://github.com/cwxyz007/vscode-hexo-utils/blob/master/TODO.md), and I will implement when I have time. Maybe the next week. 

Thanks for your advice.

**Comment by cwxyz007** [comment]
closed. Detail found in [config](https://github.com/cwxyz007/vscode-hexo-utils#extension-settings).
