### ISSUE TITLE
建议添加新功能

### ISSUE THREAD

**Issue by NanerLee** [cwxyz007/vscode-hexo-utils#12]
1. 创建 post 时, 希望能够支持父级目录的创建, 我post文件夹比较特殊, 下边有很多子目录, 也经常有创建子目录的需求.比如我在 new post 时输入 dir1/dir2/newpost 时, 能够自动帮我检测创建好dir1和dir2目录, hexo new 的命令是会把 / 替换成 -, 所以不行

2. 能否加入选项来控制 post draft, categories, tags 这几个区域是否显示, 虽然可以隐藏, 但是如果能不显示最好了

另外这个扩展很棒, 能够在写文章时更加专注了, 不会看到一大堆文件和文件夹

**Comment by cwxyz007** [comment]
第一个问题

扩展已经支持了，点击 post 的 + 按钮，然后输入类似 `dir1/dir2/newpost` 就会创建对应的 post
![image](https://user-images.githubusercontent.com/14226737/57981713-e72caf00-7a6d-11e9-885e-d2700b81f2bf.png)
![image](https://user-images.githubusercontent.com/14226737/57981739-6c17c880-7a6e-11e9-8a61-e84a4f5cd71e.png)

第二个问题

在 HEXO UTILS 那一行右键可以隐藏对应的那一栏，这是 vscode 提供的功能，所有插件都支持
![image](https://user-images.githubusercontent.com/14226737/57981703-c5cbc300-7a6d-11e9-9f1d-daa67fbdce49.png)

**Comment by NanerLee** [comment]
感谢回复和解答!

关于第一个问题, 很奇怪, 昨天在家里的电脑上操作的时候, 会给我报错, 说文件不存在. 今天在另外的电脑上是成功创建了, 要等到晚上回家再看看了

关于第二个功能, 好长时间没用过了, 我都给忘了......, 添麻烦了

**Comment by cwxyz007** [comment]
关于第一个问题，的确是我的问题，我昨天回复你之后，测试发现的确是有 bug

在 0.1.2 的版本的确支持了，可能是当时我没有测试好，用的人也不多，所以没有发现这个 “路径不存在” 的 bug

昨天我把这个 bug fixed 了，发布了一个新版本，所以现在可以用了

![image](https://user-images.githubusercontent.com/14226737/57992013-c6ec0700-7ae4-11e9-8d46-62875f6f88d8.png)

**Comment by NanerLee** [comment]
感谢, 确实正常了

不过好像作者你的 new post 好像不是通过 hexo 来做的, 我看新建出的 post 的时间格式不一样, hexo 默认的是 YYYY-MM-DD HH:mm:ss, 用扩展创建出来的是 2019-05-21T13:42:54.143Z, 不过对生成文章也不影响.

**Comment by cwxyz007** [comment]
嗯，因为 `hexo new`  命令有点慢，所以直接用 nodejs 的 fs 模块写的这一块，没有注意时间的格式，如果有需求的话，可以开一个 issue，有空我会处理，也欢迎提 PR~
