### ISSUE TITLE
More front-matters

### ISSUE THREAD

**Issue by L1cardo** [cwxyz007/vscode-hexo-utils#19]
If I create a new article , it will generate only with `title` `date` `tags`, can it be possible to have more front-matters, or it will be better to have cumtomization!
Now:
![image](https://user-images.githubusercontent.com/33802186/66764265-fe1be400-eedb-11e9-8ffa-fa364af4b905.png)
What I want:
![image](https://user-images.githubusercontent.com/33802186/66764390-43d8ac80-eedc-11e9-8b6e-69c875bc396e.png)

**Comment by cwxyz007** [comment]
Maybe you could try `create a new article` command, It will read scaffolds folder, all your template will list.

Unfortunately, it is only support `title` and `date` variables.

![image](https://user-images.githubusercontent.com/14226737/66793361-9c856500-ef2f-11e9-800a-1f3b37f10b04.png)

![image](https://user-images.githubusercontent.com/14226737/66793522-4f55c300-ef30-11e9-8358-0706ad328a3d.png)


![image](https://user-images.githubusercontent.com/14226737/66793378-b6bf4300-ef2f-11e9-9a65-a30bf56f000e.png)

**Comment by L1cardo** [comment]
我才发现是成都的老哥 哈哈哈哈 那就说中文了
我说的东西 以后能实现吗？ 更新一下？

**Comment by cwxyz007** [comment]
能不能准确的描述一下你的需求？我没太理解。。。

现在的模板能不能满足你的需求？

**Comment by L1cardo** [comment]
现在模板只有title date tags 这三个，我希望能有多一点的选项，或者可以自定义就更好了

**Comment by cwxyz007** [comment]
hexo 的模板功能有没有用过？可以自定义的，放在 `scaffolds` 文件夹里面，然后用 `create a new article` 命令就可以看到模板名称了 

![](https://user-images.githubusercontent.com/14226737/66793378-b6bf4300-ef2f-11e9-9a65-a30bf56f000e.png)

**Comment by cwxyz007** [comment]
[Hexo 模板](https://hexo.io/zh-cn/docs/writing#%E6%A8%A1%E7%89%88%EF%BC%88Scaffold%EF%BC%89)

**Comment by L1cardo** [comment]
嗯嗯 好的  麻烦你了  谢谢

**Comment by cwxyz007** [comment]
没事~
