### ISSUE TITLE
metadata error: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by tjx666** [cwxyz007/vscode-hexo-utils#21]
as screenshot:
![Snipaste_2019-11-29_15-05-39](https://user-images.githubusercontent.com/41773861/69850270-e21ca800-12b9-11ea-97b5-0172e0ad41a0.png)

**Comment by cwxyz007** [comment]
Hexo matadata format should be like this:

```md
---
title:  Title
others: something
---
```

So I think you miss `---` in the beginning.

![image](https://user-images.githubusercontent.com/14226737/69853252-54dd5180-12c1-11ea-8b2c-69963061a4b8.png)

**Comment by cwxyz007** [comment]
Official document: [Front-matter](https://hexo.io/docs/front-matter.html)

**Comment by tjx666** [comment]
You are right.
