### ISSUE TITLE
Wrong date & time generated

### ISSUE THREAD

**Issue by BillYang2016** [cwxyz007/vscode-hexo-utils#22]
**Describe the bug**
When I created a new article by this plugin (using the "+" button beside "post"), the date & time of the article was wrong, it also got an wrong date format.

**To Reproduce**
1. Go to Hexo Utils
2. Click on '+' button besides "post"
3. Open the new article

**Expected behavior**
![image](https://user-images.githubusercontent.com/26852391/74101967-05958600-4b7a-11ea-8284-54f12a0ef622.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/26852391/74101959-f4e51000-4b79-11ea-8b8a-e3707961c9bb.png)

**Plugin version(please complete the following information):**
v0.1.10

**Additional context**
The article displayed wrong date & time also after I started my hexo server.
The time I created this article was 20:08:56, but I got "2020-02-09T12:03:56.010Z" in my front-matters.
The same thing happend when I used "Create a new post" command by "Ctrl+Shift+P".
But it looked well when I used "hexo new" command to create a new article.
Thank U very much for this wonderful plugin.

**Comment by cwxyz007** [comment]
![](https://user-images.githubusercontent.com/26852391/74101959-f4e51000-4b79-11ea-8b8a-e3707961c9bb.png) This is standard [ISO](https://www.wikiwand.com/en/ISO_8601) format. And this is better to express timestamp.

So, why do you need ![](https://user-images.githubusercontent.com/26852391/74101967-05958600-4b7a-11ea-8284-54f12a0ef622.png) this format ?

**Comment by BillYang2016** [comment]
the ISO format is OK, but the time is still wrong I think.

**Comment by cwxyz007** [comment]
![image](https://user-images.githubusercontent.com/14226737/74103469-21535900-4b87-11ea-94d4-fed2a025dfc9.png)

I don't think it is wrong, because ISO format include time zone.I don't think it is wrong, because ISO format include time zone.

**Comment by BillYang2016** [comment]
Thank U for your respond, but this time is not adjusted after article generated. Maybe this is a issue from hexo theme?

**Comment by cwxyz007** [comment]
Can you provide a reproduce repository ?

**Comment by BillYang2016** [comment]
Let me have a try in an empty repo.

**Comment by BillYang2016** [comment]
I've tried creating a new article in an empty repo and using NexT as theme.
Here is what I got:
![image](https://user-images.githubusercontent.com/26852391/74103671-100b4c00-4b89-11ea-8f2c-bb18bc94bde9.png)
![image](https://user-images.githubusercontent.com/26852391/74103678-1d283b00-4b89-11ea-9183-04d2c545e56c.png)

**Comment by BillYang2016** [comment]
Default theme landscape will not display the time when articles created and escaped from this question.

**Comment by cwxyz007** [comment]
Next theme use `full_date` function to parse time, but default format is `date_format + time_format`

[NexT posted on](https://github.com/theme-next/hexo-theme-next/blob/c6ed63130700d5ca099aefef2f425fc8c67989e2/layout/_macro/post.swig#L57)

[full_date function](https://hexo.io/docs/helpers.html#full-date)

**Comment by cwxyz007** [comment]
![image](https://user-images.githubusercontent.com/14226737/74103803-26fe6e00-4b8a-11ea-84bd-515779cd66a6.png)
![image](https://user-images.githubusercontent.com/14226737/74103806-2c5bb880-4b8a-11ea-95b6-2a6a9f95ed09.png)

**Comment by BillYang2016** [comment]
So u mean this is an issue from NexT. I will post it to NexT. Thank u anyway.

**Comment by cwxyz007** [comment]
Yeah, It is a better way that solve this with NexT.

**Comment by cwxyz007** [comment]
I need correct what I said. The reason cause this bug is Hexo parse ISO time in the incorrect way.

**Comment by cwxyz007** [comment]
[hexo-front-matter](https://github.com/hexojs/hexo-front-matter/blob/69eb7d7a8cd8b564b59aaeb199dc3647eacea4c3/lib/front_matter.js#L64)

**Comment by cwxyz007** [comment]
I have expose the time format config. Please upgrade and set config `hexo.generateTimeFormat` to `YYYY-MM-DD HH:mm:ss`

**Comment by BillYang2016** [comment]
I see. Thanks a lot.

**Comment by yiyungent** [comment]
终于看到有人和我相同问题了，以前用这个插件已经生成了很多 `date` `iso8601` 了, 不好手动改，我这里写了一个 PowerShell 脚本，
对于已经有 `date:` 的则更新到 `2020-12-22 13:23:46` 形式，如没有 `date:` , 则利用 `git log` 来找到最早的时间作为 `date:`,

> 推荐使用 `PowerShell Core` 执行，配合上 `GitHub Actions` 自动更新

```yml
- name: Checkout 🛎️
   uses: actions/checkout@master
   with:
     # 为了让 git 有日志 (git log) 可寻，还得在检出的时候顺带把所有提交历史一并拉下来，指定 fetch-depth 就能做到
     fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

- name: Fix File Modify Date
   run: |
     ./fix-date.ps1
     ./updated.ps1
   shell: pwsh
```

> 附带了 用于更新 `updated:` 的 `updated.ps1`

[脚本.zip](https://github.com/0x-jerry/vscode-hexo-utils/files/10883131/default.zip)
