### ISSUE TITLE
Only activate when workspace has `_config.yml`

### ISSUE THREAD

**Issue by lengthmin** [cwxyz007/vscode-hexo-utils#24]
**Is your feature request related to a problem? Please describe.**

it's better to activate extension when needed;
so activated if workspace have related files, such as _config.yml.

**Describe the solution you'd like**
https://github.com/cwxyz007/vscode-hexo-utils/blob/master/package.json#L29

add:
        "workspaceContains:_config.yml",

**Describe alternatives you've considered**
as above.

**Additional context**
nop

**Comment by cwxyz007** [comment]
Nice idea, and do you want to make a PR? If you want, just make one.

**Comment by lengthmin** [comment]
sure, I'll make a pr it later

**Comment by lengthmin** [comment]
it seem that the actividybar's icon appear even if the plugin is not activated..

the same as the command, they are provided by package.json.

I use a toast for test.
![image](https://user-images.githubusercontent.com/13938334/79409728-38705600-7fd1-11ea-91b9-b12575b2044c.png)

so this img show that the extension are not activated, but the icon still exists.
![image](https://user-images.githubusercontent.com/13938334/79409823-73728980-7fd1-11ea-9b72-561b34ff9171.png)
