### ISSUE TITLE
Setting "Sort Method" doesn't apply to Categories and Tags

### ISSUE THREAD

**Issue by kristofzerbe** [cwxyz007/vscode-hexo-utils#26]
I find it useful to sort the drafts and posts ordered by date, descending, because I don't work with date prefixes in the title. But this setting doesn't has an effect on the lists of categories and tags. Those subitems are always sorted alphabetically.

**Comment by cwxyz007** [comment]
Good idea, I will support it in next version.

**Comment by cwxyz007** [comment]
Please upgrade to v0.1.14 and have fun :)
