### ISSUE TITLE
Folder for images?

### ISSUE THREAD

**Issue by tmmaribell** [cwxyz007/vscode-hexo-utils#30]
so that pictures are added to the "**_posts \ store \ Post_Title**" folder

How to do it?
Example: _posts \ **store** \ Post_Title \ YYYY-MM-DD-HHmmss.png

Now it works like this: _posts \ Post_Title \ YYYY-MM-DD-HHmmss.png

```
      const uri = path.parse(filePath);
      const imageFolder = path.join(uri.dir, uri.name);
      await fs.ensureDir(imageFolder);

      const name = dayjs().format('YYYY-MM-DD HHmmss.png');

      const imagePath = path.join(imageFolder, name);
```

**Comment by cwxyz007** [comment]
I don't understand why you want this feature. And this extension is for `Hexo` project, then I think you should follow [the rule](https://hexo.io/docs/asset-folders) of `Hexo`.

**Comment by tmmaribell** [comment]
it is convenient when all images are in one folder, folders with images are not scattered in the _posts folder. I need a web server with a different subdomain to look in the store folder

**Comment by cwxyz007** [comment]
I recommend this extension [vscode-paste-image](https://github.com/mushanshitiancai/vscode-paste-image). that has more configuration and can suit your needs.
