### ISSUE TITLE
Posts are created with spaces

### ISSUE THREAD

**Issue by tmmaribell** [cwxyz007/vscode-hexo-utils#31]
Example: New post

And it should be like this: New-post

And yet, the Move to Draft / Post function does not work

**Comment by cwxyz007** [comment]
I will check the first problem.

For the second one, please use https://github.com/cwxyz007/vscode-hexo-utils/issues/new?assignees=&labels=&template=bug_report.md&title= this link to report the bug. And if you can provide a repo to reproduce the bug, that will be very helpful.
