### ISSUE TITLE
Cannot read property 'filePath' of undefined

### ISSUE THREAD

**Issue by xiepeng21** [cwxyz007/vscode-hexo-utils#32]
What about the problem of "Cannot read property 'filePath' of undefined", CATEGORIES, and TAGS of the sidebar don't show success, how can I solve it? Thank you.

**Comment by cwxyz007** [comment]
Maybe the metadata info of your markdown file is not correct. So if you can provide a example file or repo to reproduce the bug, that will be very helpful.

请提供一下出错的文件，或者一个示例仓库，我猜测可能是 `markdown` 文件中的元信息不全.

正确的 `markdown` 示例如下：

```md
---
title: XXX
date: 2017-10-27 21:08:27
tags: [xxx]
---

# 标题
```

**Comment by cwxyz007** [comment]
I have fixed this, please update the extension :)

**Comment by xiepeng21** [comment]
> 
> 
> I have fixed this, please update the extension :)

It works, thank you very much. 👍
