### ISSUE TITLE
when explain categories, it have problem

### ISSUE THREAD

**Issue by jarywong** [cwxyz007/vscode-hexo-utils#36]
**Describe the bug**
when i write the categories on hexo's md files like the following
pattern 1:
```
categories:
- c1
- c2
```
pattern 2:
```
categories:
- [c1, sc1]
- [c2, sc2]
```
it will explain like the following by "hexo g", but can explain it correctly by this extension.
pattern 1:
- c1
  - c2

pattern 2:
- c1
  - sc1
- c2
  - sc2

**Plugin version(please complete the following information):**
v0.1.20

**Comment by cwxyz007** [comment]
I will take a look at how `Hexo` handle this, and thanks for your feedback.

```
categories:
- [c1, sc1]
- [c2, sc2]
```

**Comment by cwxyz007** [comment]
It Has support in version 0.1.21. Please upgrade the extension.
